#!/bin/bash
# Copyright 2018 Jordon Bedwell. All rights reserved.
# Use of this source code is governed by the MIT license
# that can be found in the LICENSE file.
[[ "$DEBUG" ]] && set -x
set -e

build_to="bins"
commit=$(git rev-parse HEAD)
version=$(git describe --abbrev=0)
go_version=$(go version | awk '{ print $3 }' | sed -e 's/^go//')
repo=$(cat go.mod | grep module | sed -e 's/^module[[:space:]]*//')
user=$(echo $repo | awk -F/ '{ print $2 }')
name=$(echo $repo | awk -F/ '{ print $3 }')
url="https://github.com"

docker pull golang:"${go_version}"
rm -r "${PWD}/${build_to}" && mkdir -p "${PWD}/${build_to}"
docker rm -f "${name}" || true

docker run --name="${name}" --env=CGO_ENABLE=0 \
  --env=GO111MODULE=on --volume="${PWD}/${build_to}:/${build_to}" \
  --workdir="/.go/src/${repo}" --detach --interactive \
  --tty golang:"${go_version}" sh

docker exec "${name}" mkdir -p "/.go/src/${repo}"
docker cp . "${name}":"/.go/src/${repo}"
if [[ "$1" ]]; then
  docker exec "${name}" git reset HEAD --hard
  docker exec "${name}" git \
    checkout "$1"
fi

build() {
  docker exec "${name}" env GOOS="${1}" GOARCH="${2}" \
    go build -v -ldflags "-s -w \
      -X ${repo}/cmd.version=${version} \
      -X ${repo}/cmd.url=${url}/${repo} \
      -X ${repo}/cmd.commit=${commit}" \
        -o "/${build_to}/${name}-${1}-${2}"
}

build linux amd64
build darwin amd64
build windows amd64
build linux arm64
build linux arm

docker rm -f "${name}"
if [[ "$SIGN" != "false" ]] && [[ "$MACOS_DEVELOPER_ID" ]]; then
  codesign -f -s "$MACOS_DEVELOPER_ID" \
    "${build_to}/${name}-darwin"-*
fi
