#!/bin/bash
// Copyright 2018 Jordon Bedwell. All rights reserved.
// Use of this source code is governed by the MIT license
// that can be found in the LICENSE file.
set -ex

rm -rf   binaries
mkdir -p binaries

env GOOS=linux   GOARCH=amd64 go build -v -ldflags '-s -w' -o binaries/tweedy-linux-amd64
env GOOS=darwin  GOARCH=amd64 go build -v -ldflags '-s -w' -o binaries/tweedy-darwin-amd64
env GOOS=windows GOARCH=amd64 go build -v -ldflags '-s -w' -o binaries/tweedy-windows-amd64
env GOOS=openbsd GOARCH=amd64 go build -v -ldflags '-s -w' -o binaries/tweedy-openbsd-amd64
env GOOS=freebsd GOARCH=amd64 go build -v -ldflags '-s -w' -o binaries/tweedy-freebsd-amd64
env GOOS=linux   GOARCH=arm64 go build -v -ldflags '-s -w' -o binaries/tweedy-linux-arm64
env GOOS=linux   GOARCH=arm   go build -v -ldflags '-s -w' -o binaries/tweedy-linux-arm
env GOOS=openbsd GOARCH=arm   go build -v -ldflags '-s -w' -o binaries/tweedy-openbsd-arm
env GOOS=freebsd GOARCH=arm   go build -v -ldflags '-s -w' -o binaries/tweedy-freebsd-arm
env GOOS=linux   GOARCH=386   go build -v -ldflags '-s -w' -o binaries/tweedy-linux-i386
env GOOS=darwin  GOARCH=386   go build -v -ldflags '-s -w' -o binaries/tweedy-darwin-i386
env GOOS=windows GOARCH=386   go build -v -ldflags '-s -w' -o binaries/tweedy-windows-i386
env GOOS=openbsd GOARCH=386   go build -v -ldflags '-s -w' -o binaries/tweedy-openbsd-i386
env GOOS=freebsd GOARCH=386   go build -v -ldflags '-s -w' -o binaries/tweedy-freebsd-i386

if [[ "$SIGN" != "false" ]] && [[ "$MACOS_DEVELOPER_ID" ]]; then
  codesign -f -s "$MACOS_DEVELOPER_ID" binaries/tweedy-darwin-*
fi
